#********************************************************************************
#                                                                               *
#                            TnFOX tests make file                              *
#                                                                               *
#********************************************************************************
#        Copyright (C) 2003-2007 by Niall Douglas.   All Rights Reserved.       *
#       NOTE THAT I DO NOT PERMIT ANY OF MY CODE TO BE PROMOTED TO THE GPL      *
#********************************************************************************
# This code is free software; you can redistribute it and/or modify it under    *
# the terms of the GNU Library General Public License v2.1 as published by the  *
# Free Software Foundation EXCEPT that clause 3 does not apply ie; you may not  *
# "upgrade" this code to the GPL without my prior written permission.           *
# Please consult the file "License_Addendum2.txt" accompanying this file.       *
#                                                                               *
# This code is distributed in the hope that it will be useful,                  *
# but WITHOUT ANY WARRANTY; without even the implied warranty of                *
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                          *
#********************************************************************************

import os
import sys
dir,name=os.path.split(os.getcwd())
if "windows" in dir or "/media/Share" in dir:
    # Replace with Unix equiv
    dir="/home/ned/"+dir[dir.find("Tornado"):]
if "/Volumes/DATA" in dir:
    # Replace with MacOS X equiv
    dir="/Users/ned/Documents/"+dir[dir.find("Tornado"):]
execfile(dir+"/../../sconslib.py")
init(globals(), dir+"/../..", dir+"/..")
targetname=dir+"/../../lib/"+architectureSpec()+"/MyTestDLL"

env['CPPDEFINES']+=[ "FOXDLL", "TESTDLL_EXPORTS" ]
env['CPPPATH']+=[ ".",
                 "../../../include"
                 ]
env['LIBPATH']+=[dir+"/../../lib/"+architectureSpec()]
env['LIBS']=[ libtnfox ]

dir+="/.."    # So the libtool hack finds the right place
if "freebsd" in sys.platform:
    env['LINK']="libtool --tag=CXX --mode=link g++" # Force always dynamic linking
elif "linux" in sys.platform:
    env['LINK']="libtool --mode=link g++ -Xcompiler -shared" # Force always dynamic linking
objects=[env.SharedObject(builddir+"/maindll", "maindll.cpp")]
Clean(targetname, objects)
if onWindows:
    env['LINKFLAGS']+=["/PDB:MyTestDLL.pdb"]
DLL=env.SharedLibrary(targetname, objects)
env.Precious(DLL)
if not onWindows:
    def runRename(target, source, env):
        stem, leaf=os.path.split(str(target[0]))
        os.system('cp '+stem+'/.libs/'+leaf+' '+stem+'/MyTestDLL.so')
    AddPostAction(DLL, Action(runRename))

if onWindows:
    env.MSVSProject("project"+env['MSVSPROJECTSUFFIX'],
                srcs=["main.cpp"],
                localincs=["../../../config.py"],
                buildtarget=DLL,
                variant=["Release","Debug"][debugmode])
    env.Alias("msvcproj", "project"+env['MSVSPROJECTSUFFIX'])
Default(DLL)
targetfrombase=targetname[3:]
Return("targetfrombase")
