#specialLibs=["TestDLL"]

def makeDLL(target, source, env):
    oldpath=os.getcwd()
    try:
        os.chdir("DLL")
        os.system('scons')
    finally:
        os.chdir(oldpath)
postbuildexecute=makeDLL
execfile("../CommonSConstruct.py")
